[build-system]
requires = ["setuptools", "wheel", "setuptools_scm", "Cython"]
build-backend = "setuptools.build_meta"

[black.tool]
line-length = 100

[tool.setuptools_scm]
write_to = "src/dnaio/_version.py"
